import json, subprocess, urllib.request, concurrent.futures as cf
K = subprocess.run(['op','item','get','Recraft AI','--vault','Cortana','--fields','API Key','--reveal'],capture_output=True,text=True).stdout.strip()
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 Chrome/126 Safari/537.36'
BASE = ("flat vector illustration, clean geometric shapes, limited palette of bright blue #009EFF, deep royal blue #0039B8, "
        "warm amber orange #FE9901 and off-white, on a plain very dark navy background #0E121A, subtle glow, modern tech brand style, no text, no letters, no people. ")
P = {'crew-hector': 'Portrait from the chest up, centered, on a plain solid very dark navy background with nothing else behind. A friendly humanoid android crew member with a human-like face: simple dark oval eyes, soft rosy cheeks and a warm closed-mouth smile, a smooth rounded off-white helmet-like head with a small blue ear light, wearing a navy starship crew jumpsuit with a colored collar and a small round mission patch. Blue collar. Friendly, welcoming expression, one hand raised in a small wave, holding a glowing envelope in the other.', 'crew-lena': 'Portrait from the chest up, centered, on a plain solid very dark navy background with nothing else behind. A friendly humanoid android crew member with a human-like face: simple dark oval eyes, soft rosy cheeks and a warm closed-mouth smile, a smooth rounded off-white helmet-like head with a small blue ear light, wearing a navy starship crew jumpsuit with a colored collar and a small round mission patch. Orange collar. Cheerful, creative expression, holding a paintbrush and a small wrench crossed in front of the chest.', 'crew-otto': 'Portrait from the chest up, centered, on a plain solid very dark navy background with nothing else behind. A friendly humanoid android crew member with a human-like face: simple dark oval eyes, soft rosy cheeks and a warm closed-mouth smile, a smooth rounded off-white helmet-like head with a small blue ear light, wearing a navy starship crew jumpsuit with a colored collar and a small round mission patch. Amber yellow collar, small round glasses. Calm, trustworthy expression, holding a small paper receipt with a check mark and a few shiny coins.', 'crew-bjorn': 'Portrait from the chest up, centered, on a plain solid very dark navy background with nothing else behind. A friendly humanoid android crew member with a human-like face: simple dark oval eyes, soft rosy cheeks and a warm closed-mouth smile, a smooth rounded off-white helmet-like head with a small blue ear light, wearing a navy starship crew jumpsuit with a colored collar and a small round mission patch. Teal collar. Confident, protective expression, holding a small round glowing shield with a keyhole in front of the chest.', 'crew-desk': 'A group of four friendly humanoid android crew members with human-like faces, simple dark oval eyes, rosy cheeks and warm smiles, smooth rounded off-white helmet-like heads, navy starship crew jumpsuits with blue, orange, amber and teal collars, standing together shoulder to shoulder, waving, in front of a big friendly round clock with gears, on a plain solid very dark navy background, centered.'}

def gen(item):
    name, p = item
    body = json.dumps({"prompt": BASE + p, "model": "recraftv4_1_vector", "size": "1024x1024"}).encode()
    req = urllib.request.Request('https://external.api.recraft.ai/v1/images/generations', data=body, headers={'Content-Type':'application/json','Authorization':'Bearer '+K,'User-Agent':UA})
    try: d = json.loads(urllib.request.urlopen(req, timeout=200).read() or b'{}')
    except Exception as e: return name, 'ERR '+str(e)[:160]
    if 'data' not in d: return name, 'ERR '+json.dumps(d)[:200]
    svg = urllib.request.urlopen(urllib.request.Request(d['data'][0]['url'], headers={'User-Agent':UA}), timeout=120).read()
    open(name+'.svg','wb').write(svg); return name, f'ok {len(svg)//1024}KB'
with cf.ThreadPoolExecutor(3) as ex:
    for n, r in ex.map(gen, P.items()): print(n, r, flush=True)
